/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package part_pds;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.DecimalFormat;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author RubenEdery
 */
public class Graphiques extends javax.swing.JFrame {
        CalcAm c = new CalcAm();
	public JPanel contentPane;
	public ChartPanel pan;
        DecimalFormat df = new DecimalFormat("0.00");// Convertir un double avec 2 chiffres apres la virgule

    /**
     * Creates new form Graphiques
     */
    public Graphiques() {
        initComponents();
        graph();
    }

    
    
   public void graph() {
		
	        DefaultPieDataset test = new DefaultPieDataset();
                test.setValue("Capital amorti "+df.format(c.getTotalinteret()/c.getTotalmensualite()*100)+"%", c.getMontant());
	        test.setValue("Interets "+c.getTaux()*100+"%", c.getTaux()*100);
	        test.setValue("Assurance "+c.getTauxdassurance()+"%",c.getTauxdassurance());
	        JFreeChart chart = ChartFactory.createPieChart("Répartition Capital Amorti/Interets/Assurance", test, true, true, true);
	        
	        pan = new ChartPanel(chart, false);
	        pan.setBounds(0, 0, 390, 300);
	        getContentPane().add(pan, BorderLayout.NORTH);
	        //JButton btnImprimer = new JButton("Imprimer");
	           
                System.out.println(df.format(c.getTotalassurance())+df.format(c.getTotalassurance())+""+df.format(c.getTotalinteret()));
	        // 4800  10000  413
                // 14000/15213 = 0,92
                
                // System.out.println((c.getTotalassurance()+c.getTotalmensualite())/(c.getTotalassurance()+c.getTotalinteret()+c.getTotalmensualite()));
                System.out.println((c.getTotalassurance()+c.getTotalmensualite()));
                //getContentPane().add(btnImprimer, BorderLayout.SOUTH);
	        this.setVisible(true);
	        this.setSize(500,500);
                this.setExtendedState(this.MAXIMIZED_BOTH);

	        	

	        
	        
	}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printChart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        printChart.setText("Imprimer");
        printChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printChartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(388, Short.MAX_VALUE)
                .addComponent(printChart)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(printChart)
                .addContainerGap(392, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printChartActionPerformed
       // TODO add your handling code here:
       PrinterJob job = PrinterJob.getPrinterJob();
         job.setPrintable(pan);
         boolean ok = job.printDialog();
         if (ok) {
             try {
                  job.print();
             } catch (PrinterException ex) {
              /* The job did not successfully complete */
             }
         }
       
    }//GEN-LAST:event_printChartActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graphiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graphiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graphiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graphiques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graphiques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton printChart;
    // End of variables declaration//GEN-END:variables
}
